# Change these first
owner: Brief-Tech-Pte # Your GitHub organization or username, where this repository lives
repo: brieftech-uptime # The name of this repository

sites:
  - name: Front End (Prod)
    url: https://discover.brieftech.ai
  - name: Back End (Prod)
    url: https://asia-southeast1-brief-tech.cloudfunctions.net/genCall2
    icon: https://discover.brieftech.ai/favicon.ico
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"data":{"function":"getVersionInfo","syncVersion":8}}'
  - name: Home Page
    url: https://brieftech.ai

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.brieftech.ai
  # baseUrl: /brieftech-uptime
  logoUrl: https://discover.brieftech.ai/icons/safari-pinned-tab.svg
  name: BriefTech Status
  introTitle: "BriefTech Uptime Server Status Monitoring"
  introMessage: This is the uptime monitoring page for BriefTech
  icon: https://discover.brieftech.ai/favicon.ico
  navbar:
    - title: Status
      href: /
    - title: Network Test
      href: /brieftech-uptime/network.html
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
